server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm
    username: sulaiman
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true


